version: "3.8"

services:
  server: 
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 25565:25565
    stdin_open: true
    tty: true
    restart: unless-stopped